### ISSUE TITLE
MatchIt should warn against matching without caliper

### ISSUE THREAD

**Issue by MetaEntropy** [kosukeimai/MatchIt#110]
By default, the matchit() function uses caliper=NULL and replace=FALSE, and so, may match observations that are extremely different.
If the treated and untreated sample sizes are equal, it will pair everybody, and the matched and unmatched cohorts will be identical, leading to no adjustment at all!

That is quite dangerous, especially because few of the top ten Google results for "propensity score R" warn about that...
On the contrary, they show examples of use of MatchIt::matchit() without any caliper.
In my opinion, a caliper is always needed, but I understand that, for backward compatibility, the behavior is kept unchanged. However, a warning message would help.

# Steps to reproduce
```
N=200

set.seed(2022) # for reproductibility
prop=runif(N) # actual propensity to be treated
treatment=!!rbinom(N,size=1,prob=prop) # who is actually treated ?
outcome=prop+rnorm(N)*0.5 # the outcome is independent of the actual treatment but depends on the propensity

library(MatchIt)
# we try to match observations without any caliper (default behavior)
mod = matchit(data=data.frame(prop=prop,treatment=treatment), treatment~prop)
# we identify indices of matched treated and untreated observations
treated=as.integer(rownames(mod$match.matrix))
control=as.integer(as.vector(mod$match.matrix))

# the confidence interval does not contain the zero value (actual treatment effect)
t.test(outcome[treated], outcome[control],paired=TRUE)

# because, the propensities are very different between groups
t.test(prop[treated], prop[control],paired=TRUE)

# the actual difference between the propensity score of treated and untreated patients
# can be huge (0.63 in this example)
max(abs(mod$model$fitted.values[treated] - mod$model$fitted.values[control]),na.rm=TRUE)
```
# Expected behavior

Warn that patients with very different propensity score have been matched, inviting to specify a caliper.

# Observed behavior

No warning at all.

# System information
Package: MatchIt
 Version: 4.3.4
 Maintainer: Noah Greifer <noah.greifer@gmail.com>
 Built: R 4.1.3; x86_64-w64-mingw32; 2022-04-12 00:05:27 UTC; windows

R Version:
 platform = x86_64-w64-mingw32
 arch = x86_64
 os = mingw32
 system = x86_64, mingw32
 status = 
 major = 4
 minor = 1.3
 year = 2022
 month = 03
 day = 10
 svn rev = 81868
 language = R
 version.string = R version 4.1.3 (2022-03-10)
 nickname = One Push-Up

Windows 7 x64 (build 7601) Service Pack 1

Locale:
 LC_COLLATE=French_France.1252;LC_CTYPE=French_France.1252;LC_MONETARY=French_France.1252;LC_NUMERIC=C;LC_TIME=French_France.1252

Search Path:
 .GlobalEnv, package:MatchIt, package:stats, package:graphics, package:grDevices, package:utils, package:datasets,
 package:methods, Autoloads, package:base

This package has a bug submission web page, which we will now attempt
to open.  The information above may be useful in your report.
If the web page does not work, you should send email to the maintainer,
Noah Greifer <noah.greifer@gmail.com>.

**Comment by ngreifer** [comment]
Hi André, thank you for the suggestion. There are a few reasons why I don't want to implement a warning for distant pairs.

First, I disagree that a caliper is always needed. Using a caliper changes the estimand, discards additional units, and can make balance worse (King & Nielseon, 2019). There is no specific value of a caliper that works for all cases, so there is no way to select a valid default caliper value. There are many other ways of achieving balance while retaining the estimand, like matching with replacement, full matching, subclassification, or template matching. Using a caliper with 1:1 matching can be helpful and it should be one of many methods tried, but it should not be the default, especially since using a caliper affects the interpretability of the effect estimate (i.e., who does the effect generalize to?).

Second, close pairs are not required for unbiased effect estimation. They can help, but what is required is covariate balance. Assessing covariate balance is explained in the `MatchIt` vignettes in detail, demonstrated in all of the `matchit()` documentation files, and recommended in every guide on performing and reporting a matching analysis. Balance and remaining sample size are the sole characteristics by which a matched sample should be judged. It is true that having close pairs tends to improve balance, but this is not always the case, and there will always be tradeoffs. In general, it is usually more beneficial to place calipers on prognostically important or hard-to-balance covariates directly than on the propensity score, since having pairs close on the propensity score does not guarantee the pairs will be close on the covariates. If you had taken the necessary step of assessing balance in your matched sample, you would see that balance actually got _worse_ after matching and you should not proceed with effect estimation until better balance is achieved.

Third, warnings can be an effective way to alert the user of unexpected behavior, but a warning for distant pairs or poor balance would be too intrusive given that the user is already expected to assess balance after matching. We do provide a warning for when not all treated units can be matched because of exact matching constraints or because the treated group is larger than the control group (which occurs in this dataset). These warnings identify to the reader that `matchit()` cannot implement matching as they intended, so it is worth warning them that `matchit()` failed to implement their requested matching method. In contrast, poorly matched groups do not warrant a warning because that is simply a possible and natural result of matching, even when the user's requests are obeyed. It is just a quality of the resulting matched sample. Including a warning for poor matches would be like including a warning for low R2 every time someone ran a regression; too intrusive given that the regression ran smoothly; it just happened to yield an undesirable result.

Given that such a warning would be intrusive, the warning refers to a quality that is not the quality by which a matched sample should be judged, and a caliper is not the only or best solution to solving the problem, I don't think it would be a good idea to warn users about distant pairs after matching.

I'm open to disagreements about the above points and welcome any other suggestions you have. Thank you for reaching out.

- Noah
