### ISSUE TITLE
How does MatchIt calculate Mean for factors/categories?

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [kosukeimai/MatchIt#121]
With matchit I see output like this

```
Summary of Balance for Matched Data:
                                                               Means Treated Means Control Std. Mean Diff.
distance                                                              0.0116        0.0116          0.0006
geschlechtMännlich                                                    0.3046        0.3126         -0.0174
geschlechtWeiblich                                                    0.6954        0.6874          0.0174
```

The variable `geschlecht` (`sex`) only has two expressions (`Männlich` means `male` and `Weiblich` means `female`). This is a `factor` when I ask `class()`.

But how does MatchIt calculate a Mean out of it when it is just a non-numeric factor? What happens in the back?

See: https://stats.stackexchange.com/q/584234/126967

**Comment by ngreifer** [comment]
It separates the factor into dummy (0/1) variables using `model.matrix()`. The mean for each dummy variable is the proportion of units with that level of the original factor. If matching weights are involved, this is a weighted mean. The sum of the means in each treatment group for all levels of each factor will be 1.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I think about if and how this can help me to decide the `ratio` of my matches. Usualy I use the _standard mean difference_ and the _variance ratio_ for that. But does this values making sense in the case of a factor. Do I have to interpret them a different way?

**Comment by ngreifer** [comment]
Variance ratios are not reported for binary variables because they don't make sense; the variance of a binary variable is solely a function of its proportion, and the difference in proportions is measured by the (standardized) mean difference.

The standardized mean difference is computed in the usual way using the formulas described in [Austin (2009)](https://doi.org/10.1080/03610910902859574). In `cobalt`, mean differences are **un**standardized by default because it doesn't make a lot of sense to standardize them, since they are already on a uniform, interpretable scale. See my rationale [here](https://ngreifer.github.io/cobalt/articles/cobalt.html#distinguishing-continuous-and-binary-covariates). In `MatchIt`, we use standardized mean differences for consistency, even for binary variables. The `eCDF max` statistic is equal to the unstandardized mean difference (i.e., the difference in proportion), so if you want that value it is there too. You can also set `standardize = FALSE` in `summary()` to only get unstandardized mean differences for all variables. SMDs will always be smaller for binary variables than unstandardized mean differences, so if you are seeking balance, making sure all SMDs are small also guarantees all differences in proportion are small, too.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Thanks a lot for your patience to describe such complex things to a statistic noob!
