### ISSUE TITLE
Summary of balance on variables - redundant and error variables created

### ISSUE THREAD

**Issue by ginnydang** [kosukeimai/MatchIt#141]
I used summary() to check the balance of variables on my data, I have some variables such as: gender, age, COPD, diabetes...
gender: F or M
COPD, diabetes: 0 or 1
age: numeric 

It's supposed to return:

genderF
genderM
age
COPD
diabetes

But my output was:
genderF
genderM
genderM
age
COPD0
COPD1
diabetes

In my ouput, genderM was mentioned twice and the second genderM doesn't have any value when I plot it. Means Treated for second genderM is 0.00000. Diabetes seemed to be fine, but COPD was categorized as COPD0 and COPD1. Diabetes also has values of 0 and 1 as well. 

I look forward to your answer and support. Thank you so much!

**Comment by ngreifer** [comment]
This could be explained by some issues with your data, so I’m going to ask you to verify a few things. 

The phenomenon with gender could occur if you actually have 3 levels of gender and two of them look the same, e.g., because one of them has a space after it due to a data entry error. Can you please verify that this is not the case by running table() on that variable and showing me the result?

The phenomenon with COPD could occur if the variable is actually stored as a character or factor even though it only takes on two values. Can you please verify this is not the case by running class() on that variable and showing me the result?

Thanks.

**Comment by ginnydang** [comment]
Thank you so much for your quick response!

You're right about the variable gender. Please see attached below
<img width="655" alt="1" src="https://user-images.githubusercontent.com/107514318/209218644-0753d8f8-f87b-40e8-9a77-18fa9b4e5d57.png">

I have problem with variable CKD (values: 0 and 1)
Originally, it was stored as "integer"
after I ran summary() to check balance, I got this error message: 
<img width="649" alt="2" src="https://user-images.githubusercontent.com/107514318/209218807-0ee9c9ed-acc8-4fa3-8ae3-00f0318ce75e.png">

At first, I had the same issue as #138. On issue #138: you made the fix and updated it on github but I had some problem with firewall at my company so I can't download anything from github. I actually had to download MatchIt zip file from Cran to local and install it manually inside R studio. That's why I manually convert CKD into factor to fix #138 issue. So now CKD is factor if I want to run summary().

**Comment by ginnydang** [comment]
Hi Noah,

the issue is resolved, I only converted character variables to factor and keep the other integer variables intact. 

Thank you so much :D
