### ISSUE TITLE
Caliper not working as intended on versions 4.5.1 - 4.5.3

### ISSUE THREAD

**Issue by JulieVu** [kosukeimai/MatchIt#163]
I was using version 4.5.2 as of 6-7 days ago and seeing the following set of results that change as expected when I change the caliper from 0.1 to 0.5. 

![Screenshot (11)](https://user-images.githubusercontent.com/13172354/232797117-467ad60a-2b9c-421d-af86-585ca9b0d0a5.png)
![Screenshot (12)](https://user-images.githubusercontent.com/13172354/232797159-ce1b508b-2805-4180-a6aa-5d9851f6fc4b.png)

However, my students started working on the assignment yesterday and installed version 4.5.3 obtained the following results, in which the number of matched pairs doesn't change when the caliper is changed.

![Screenshot (13)](https://user-images.githubusercontent.com/13172354/232797676-c7de8863-782f-4c5e-953b-e6d17ca5a57d.png)
![Screenshot (14)](https://user-images.githubusercontent.com/13172354/232797701-c7e80152-ae18-474e-a9c8-1f3e87ebb49f.png)

Additionally, when I installed version 4.5.2 just now on a different machine than the one I was originally using 6-7 days ago, I couldn't replicate the original set of results; i.e., I got the same results as with version 4.5.3. So it appears that the version 4.5.2 available on CRAN changed between today and last week? I wasn't able to replicate the original results in the first pair of screenshots until rolling back to version 4.5.0.

Hat tip to Victoria for posting about this on CV: https://stats.stackexchange.com/questions/612858/matchit-specified-caliper-still-matches-everyone

**Comment by JulieVu** [comment]
I was also very surprised that it would be possible to obtain two different results with version 4.5.2 just based on a different installation date...! 

Yes, I ran that code and `summary()` produced the following:

```
> summary(m0)

Call:
matchit(formula = treat ~ age + educ + race + married + nodegree + 
    re74 + re75, data = lalonde, caliper = 0.1)

Summary of Balance for All Data:
           Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean eCDF Max
distance          0.5774        0.1822          1.7941     0.9211    0.3774   0.6444
age              25.8162       28.0303         -0.3094     0.4400    0.0813   0.1577
educ             10.3459       10.2354          0.0550     0.4959    0.0347   0.1114
raceblack         0.8432        0.2028          1.7615          .    0.6404   0.6404
racehispan        0.0595        0.1422         -0.3498          .    0.0827   0.0827
racewhite         0.0973        0.6550         -1.8819          .    0.5577   0.5577
married           0.1892        0.5128         -0.8263          .    0.3236   0.3236
nodegree          0.7081        0.5967          0.2450          .    0.1114   0.1114
re74           2095.5737     5619.2365         -0.7211     0.5181    0.2248   0.4470
re75           1532.0553     2466.4844         -0.2903     0.9563    0.1342   0.2876

Summary of Balance for Matched Data:
           Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean eCDF Max Std. Pair Dist.
distance          0.5774        0.3629          0.9740     0.7564    0.1321   0.4216          0.9740
age              25.8162       25.2054          0.0854     0.4633    0.0839   0.2541          1.3893
educ             10.3459       10.5838         -0.1183     0.5862    0.0222   0.0649          1.2205
raceblack         0.8432        0.4703          1.0259          .    0.3730   0.3730          1.0259
racehispan        0.0595        0.2108         -0.6400          .    0.1514   0.1514          1.0514
racewhite         0.0973        0.3189         -0.7478          .    0.2216   0.2216          0.8208
married           0.1892        0.2000         -0.0276          .    0.0108   0.0108          0.8005
nodegree          0.7081        0.6486          0.1308          .    0.0595   0.0595          0.9868
re74           2095.5737     2476.9475         -0.0780     1.2629    0.0546   0.2865          0.8160
re75           1532.0553     1669.7419         -0.0428     1.4712    0.0508   0.2108          0.7552

Sample Sizes:
          Control Treated
All           429     185
Matched       185     185
Unmatched     244       0
Discarded       0       0

> summary(m)

Call:
matchit(formula = treat ~ ps, data = lalonde, distance = "euclidean", 
    caliper = c(ps = 0.1))

Summary of Balance for All Data:
   Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean eCDF Max
ps        0.5774        0.1822          1.7941     0.9211    0.3774   0.6444

Summary of Balance for Matched Data:
   Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean eCDF Max Std. Pair Dist.
ps        0.4958        0.4932           0.012     1.0119    0.0049   0.0631          0.0245

Sample Sizes:
          Control Treated
All           429     185
Matched       111     111
Unmatched     318      74
Discarded       0       0
```

**Comment by vdixit005** [comment]
One thing I can add here, is that it probably is an Rcpp issue. When I install the "MatchIt" package, I get warnings of the like,
![image](https://user-images.githubusercontent.com/31857521/233114325-30f2f3f2-aa9a-4b20-9b38-1fa4b3b69d9e.png)

**Comment by ngreifer** [comment]
@vdixit005 That's very helpful, thank you!

**Comment by ngreifer** [comment]
Actually, that is a separate issue because that's not the function where the originally reported error is occurring. I think those warnings are benign. Could both of you tell me what platform you're using and what version of `Rcpp` you have installed? And could you try updating `Rcpp` if it is not the most updated version?

**Comment by vdixit005** [comment]
I am using --
R version 4.1.3 (2022-03-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS
R cpp 1.0.10

**Comment by ngreifer** [comment]
Thank you. It might be worth updating R (your version is over a year old, and I think some new standards for how C++ is used were added recently). I should make sure `MatchIt` is compatible with older versions of R, but that might solve your issues with the warnings.

@JulieVu, that might solve your problems, too, if you're using an old version of R. I am certain the issue is with the compiler. When you used `MatchIt` 4.5.2 previously, you were likely using a compiled version (i.e., compiled by CRAN). When you re-installed it after updating to 4.5.3, your own computer had to compile it. I'm guessing there is a difference in the compilation between your computer and CRAN's (and mine) that is responsible for the issue. It would be worth trying to update R to the most recent version (and having your students do the same) and try again. Sorry for making you go through this; I will work on making sure `MatchIt` is backward compatible.

**Comment by JulieVu** [comment]
I didn't see any of the above warnings when I tried the installation.

It's possible I am using an old version of R, but I currently can't check
as I was accessing R via the Harvard FAS OnDemand studio which is
experiencing some downtime right now. I am not sure that would be the
issue, though, since I would expect the server to be on the latest version.
I will check once the server goes back up.

I was originally using Matchit 4.5.2 on my local machine (and not seeing
the issue with caliper):
R version 4.4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32
R cpp 1.0.10

**Comment by ngreifer** [comment]
Thank you for the info! I didn't know you were at Harvard; I am too.

**Comment by vdixit005** [comment]
Thank you @ngreifer . Yeah, it could be because of the R verison. When I try the same on a different system, which has an updated R version I don't see the warnings and the caliper example works as intended under version 4.5.3.

**Comment by JulieVu** [comment]
Yes, I am in the FAS Statistics department! Ok, the OnDemand service is
back up. Turns out the R version is not current.

R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu
R cpp 1.0.10

Unfortunately, I do not think I have the necessary permissions to update R
on OnDemand.

**Comment by albwe** [comment]
I am experiencing this issue too I am afraid - and with R 4.3.0, the most recent version on the R website and MatchIt 4.5.3. I can replicate the example of @ngreifer with lalonde in the exact same way as @JulieVu. Is there any chance of resolution, I really need the caliper to work.

**Comment by ngreifer** [comment]
@albwe I'm so sorry you're experiencing this. I'm working on a solution but it's hard for me to know where the problem is given that I can't replicate it myself.

I made a development version of `MatchIt` in which I attempt to solve the problem. Can you please try installing this version and see if you encounter the same problem?

[MatchIt_4.5.3.9001.tgz](https://github.com/kosukeimai/MatchIt/files/11453640/MatchIt_4.5.3.9001.tgz)

You can install this by running
```r
install.packages("https://github.com/kosukeimai/MatchIt/files/11453640/MatchIt_4.5.3.9001.tgz", repos = NULL)
```
and then restarting R. Please let me know if this solves it.

If not, I already provided a workaround [above](https://github.com/kosukeimai/MatchIt/issues/163#issuecomment-1513321647) (i.e., estimate the propensity score outside `matchit()`, supply it as the sole covariate to `matchit()`, and request Euclidean distance matching). To assess balance on the covariates using `summary()`, just supply those variables to the `addl` argument.

**Comment by ngreifer** [comment]
Okay, with some help from some other developers, I have solved the problem. You can install an updated version of `MatchIt` using
```r
remotes::install_github("ngreifer/MatchIt")
```
This will make its way to CRAN in the next week or so. So sorry for the confusion, everyone.

**Comment by JulieVu** [comment]
Thanks so much for your help!

**Comment by albwe** [comment]
Yes! Thanks you really much for this quick update! It works perfectly now. 
This might be the right time to say that I find this package really helpful and I am very grateful that you and others have built it.
P.S.: I hope my request above was not too arrogating, it was just my German bluntness ;-)
