### ISSUE TITLE
Very difference Matching Results using R matchit compared to SAS PSmatch

### ISSUE THREAD

**Issue by 49470952** [kosukeimai/MatchIt#173]
I ran into some discrepancy while migrating from SAS PSmatch to R matchit and trying to figure out what is causing the difference in matching results.

I created a small dataset and ran it through both SAS and R to compare the matching results. All the parameters were set to be the same including matching method (nearest neighbor matching), sorting method (data are sorted by descending propensity score), common support (yes), caliper width (0.2), etc. I attached the sample data and matching results below for reference.
 
My question is with the exact same setting, why SAS and R output very different matched pairs? Aren’t matches based on the closest logit propensity score within caliper width? It looks to me the R matched pairs had very different logit propensity score while SAS pairs looked closer. Aren’t matching based on the closest logit propensity score within caliper width? In addition, when I tuned the caliper width in R from 0.05 to 0.5, it did not impact the matching results at all. Is caliper width calculated the same way in R as SAS? Why change it does not impact the R matching results?

Any feedbacks will be greatly appreciated! Thanks.

[SAS and R Matching Comparison.xlsx](https://github.com/kosukeimai/MatchIt/files/12116613/SAS.and.R.Matching.Comparison.xlsx)

**Comment by ngreifer** [comment]
You were not matching using the same specifications as `PROC PSMATCH`. In `matchit()`, you were matching on the propensity score, and in SAS, you were matching on the logit of the propensity score. Setting `link = "linear.logit"` in the call to `matchit()` matches on the logit of the propensity score. In `PROC PSMATCH`, using `region = cs` extends the region of common support based on the `extend` argument, which by default is .25. In this sample, almost no units were removed due to the common support restriction. In `matchit()`, the `discard` option is a strict cutoff right at the edges of the propensity score distribution for each treatment group, which you can request in `PROC PSMATCH` by setting `extend = 0`. However, doing this in combination with the caliper should leave you with no matches. Removing the `discard` option in `matchit()` (since it is basically inactive in `PROC PSMATCH` anyway) and setting `link = "linear.logit"` gives the same results between the two packages.

My guess as to why you are getting any matches at all when using `matchit()` is that you are using an older version of `MatchIt` that has a bug in the application of calipers. Can you confirm you are using the most recent version of `MatchIt`? When I run your code using the most recent version, no matches are found.

**Comment by 49470952** [comment]
Thank you so much for the help, I really appreciated it!! I updated MatchIt to version 4.5.4. and removed discard option as suggested, now I am getting the same result as SAS.
