### ISSUE TITLE
Data needs to be randomized before sending it to matchit. Is this desired behaviour?

### ISSUE THREAD

**Issue by harttu** [kosukeimai/MatchIt#180]
Hello,

I discovered that Matchit does not randomize the data. In the example script, I am using covariate AGE to predict IS_CASE. However, the algorithm picks the first occurrence from each group resulting in a biased output since the data was arranged by DAY_OF_BIRTH beforehand, which is not a covariate in this case. Do you know if this is desired behaviour?
```R
# Example code
library(MatchIt)
library(tidyverse)

data <- tribble(
  ~AGE , ~DAY_OF_BIRTH , ~IS_CASE,
  # CONTROLS
    30 , 1             , F ,                
    30 , 2             , F ,
    30 , 3             , F ,
    40 , 1             , F ,
    40 , 2             , F ,
    40 , 3             , F ,
    50 , 1             , F ,
    50 , 2             , F ,
    50 , 3             , F ,
  # CASES
    30 , 1             , T ,
    40 , 1             , T ,
    50 , 1             , T
)

# This produces always DAY_OF_BIRTH = 1, even though it is not covariate
data_sorted = data
m_out <- matchit( IS_CASE ~ AGE, data = data_sorted,method = "nearest")
m_data <- match.data(m_out) # Only controls with DAY_OF_BIRTH = 1 are selected
m_data %>% filter( IS_CASE ) %>% 
  inner_join(m_data %>% filter(! IS_CASE ), by = "subclass")

# This produces random results for covariate, but sometimes needs to be rerun several times
# for the sake of randomnity to get clear results
data_random_sorted = slice(data,sample(1:nrow(data)))
m_out <- matchit( IS_CASE ~ AGE, data = data_random_sorted,method = "nearest")
m_data <- match.data(m_out) # selects DAY_OF_BIRTH 1 , 2 and 3 as expected 
m_data %>% filter( IS_CASE ) %>% 
  inner_join(m_data %>% filter(! IS_CASE ), by = "subclass")
```

**Comment by ngreifer** [comment]
In the case of ties, `matchit()` will use the control unit closest to the top of the input data. There is no other principled way to make this decision and we need to make sure results are replicable across runs without a seed. I agree it is arbitrary but shuffling your dataset is a good way to avoid any biases that might occur due to this. If you have any other suggestions feel free to let us know.

**Comment by harttu** [comment]
Would it be better if  the data was randomized anyhow but with a  fixed seed by default? That way the runs should be replicable and it is guaranteed that the results are not biased. I have used MatchIt several times in research but only now discovered this feature and it might have resulted to some biases.

**Comment by ngreifer** [comment]
That is an interesting idea, thank you for the suggestion. I think for now I will just document this behavior better so users are aware of the implications of ordering their data. In practice, this would only lead to more similar, not less similar, matched pairs, so I don't think the bias is really anything to worry about. Most users match with many variables, which reduces the likelihood of exact ties, anyway.

**Comment by tommmmi** [comment]
As a colleague of @harttu, this caught my attention and I also wanted to test this on a small dataset and noticed a bit strange behaviour in case of ties.

My data was:

```R
    id age group cancer feature
1    1  19     A   TRUE       1
2    2  20     B   TRUE       1
3    3  21     C   TRUE       1
4  101  28     A   TRUE       0
5  102  29     B   TRUE       0
6  103  30     C   TRUE       0
7  201  17     A   TRUE       0
8  202  18     B   TRUE       0
9  203  19     C   TRUE       0
10 301  19     A  FALSE       0
11 302  20     B  FALSE       0
12 303  21     C  FALSE       0
13 401  19     A   TRUE       0
14 402  20     B   TRUE       0
15 403  21     C   TRUE       0
```

If I use propensity score matching on `age` and `group`:

```R
matchit(feature ~ age + group, data = ddd, method = "nearest") -> m_ddd

match.data(m_ddd) -> m_ddd_data
  
merge(m_ddd_data[m_ddd_data$feature == 1,],
      m_ddd_data[m_ddd_data$feature == 0,], by = "subclass") -> m_ddd_matches

m_ddd_matches
```

I get:

```R
  subclass id.x age.x group.x cancer.x feature.x distance.x weights.x id.y age.y group.y cancer.y feature.y distance.y weights.y
1        1    1    19       A     TRUE         1  0.2194883         1  301    19       A    FALSE         0  0.2194883         1
2        2    2    20       B     TRUE         1  0.2194883         1  302    20       B    FALSE         0  0.2194883         1
3        3    3    21       C     TRUE         1  0.2194883         1  303    21       C    FALSE         0  0.2194883         1
```

The resulted case-control pairs are exact match in terms of age and group - as they should be - of either id's 301-303 or 401-403 to id's 1-3, and in this case: id's 1-3 are matched to id's 301-303 because they appear first in the data. This seems to be OK and correct.

I also confirmed that they all (1-3, 301-303, 401-403) have the same predicted values of logistic function (`distance` variable):

```R
m_ddd_dist <- m_ddd$distance
cbind(ddd[as.numeric(names(m_ddd_dist)),], m_ddd_dist)
```

```R
    id age group cancer feature m_ddd_dist
1    1  19     A   TRUE       1 0.21948832
2    2  20     B   TRUE       1 0.21948832
3    3  21     C   TRUE       1 0.21948832
4  101  28     A   TRUE       0 0.06209728
5  102  29     B   TRUE       0 0.06209728
6  103  30     C   TRUE       0 0.06209728
7  201  17     A   TRUE       0 0.27943777
8  202  18     B   TRUE       0 0.27943777
9  203  19     C   TRUE       0 0.27943777
10 301  19     A  FALSE       0 0.21948832
11 302  20     B  FALSE       0 0.21948832
12 303  21     C  FALSE       0 0.21948832
13 401  19     A   TRUE       0 0.21948832
14 402  20     B   TRUE       0 0.21948832
15 403  21     C   TRUE       0 0.21948832
```

Next, I wanted to see how does it select the rows, and I simply reversed the row order of the data.

```R
ddd[nrow(ddd):1,] -> ddd
```

After re-running the matching, I get a result in reversed order, but it still "chooses" the id's 301-303 and not the 401-403:

```R
  subclass id.x age.x group.x cancer.x feature.x distance.x weights.x id.y age.y group.y cancer.y feature.y distance.y weights.y
1        1    3    21       C     TRUE         1  0.2194883         1  303    21       C    FALSE         0  0.2194883         1
2        2    2    20       B     TRUE         1  0.2194883         1  302    20       B    FALSE         0  0.2194883         1
3        3    1    19       A     TRUE         1  0.2194883         1  301    19       A    FALSE         0  0.2194883         1
```

Remember, the data is now reversed, so id's 401-403 are now closest to the top of the input data. Still, it is picking up id's 301-303 after them?

Something even more strange happened when I continued this experiment by sorting the data by descending `cancer` status:

```R
ddd[order(-ddd$cancer),] -> ddd
```

Now the data looks like this:

```R
    id age group cancer feature
1  403  21     C   TRUE       0
2  402  20     B   TRUE       0
3  401  19     A   TRUE       0
4  203  19     C   TRUE       0
5  202  18     B   TRUE       0
6  201  17     A   TRUE       0
7  103  30     C   TRUE       0
8  102  29     B   TRUE       0
9  101  28     A   TRUE       0
10   3  21     C   TRUE       1
11   2  20     B   TRUE       1
12   1  19     A   TRUE       1
13 303  21     C  FALSE       0
14 302  20     B  FALSE       0
15 301  19     A  FALSE       0
```

If I re-run the matching, the result is inconsistent with the both previous runs:

```R
  subclass id.x age.x group.x cancer.x feature.x distance.x weights.x id.y age.y group.y cancer.y feature.y distance.y weights.y
1        1    3    21       C     TRUE         1  0.2194883         1  401    19       A     TRUE         0  0.2194883         1
2        2    2    20       B     TRUE         1  0.2194883         1  402    20       B     TRUE         0  0.2194883         1
3        3    1    19       A     TRUE         1  0.2194883         1  403    21       C     TRUE         0  0.2194883         1
```

Now, for some reason, it matches id 3 to id 401, and not to id 403 which appears first in the dataset? Also, this is not any more exact match - actually - it's not matching at all on `age` and `group`, but on `distance` parameter. Is it sorting the data based on `distance` somewhere within the `matchit()` function in order to define `subclass` for each id?

My thought here was that; in case of ties, if this kind of sorting is happening based on `distance`, should it also make sure that the parameters the matching is based on (in this case, `age` and `group`), be taken into account in sorting and defining `subclass` for each row?

I exercised this on a larger datasets too, and the behaviour illustrated here seems to show up only in the case of ties (equal `distance`).

**PS**. I wanted to illustrate the importance of the order of the rows in the data with the `cancer` variable in the data. As you can see the example results I provided here, if the one who is doing the matching does not take into account all the variables available in the data (this is often the case that the matching is first performed on secondary/background variables, and after matching the actual analyses are applied on variables that actually are the interested ones), it might lead to a substantially different pool of controls (i.e. ones with cancer vs. ones with not). This is not a critic against the package nor the function, but just something that everyone doing matching **should be aware of**.

**Comment by ngreifer** [comment]
Hi Tommi,

Thank you for looking into this and I'm so sorry for any confusion. Most of this is expected but undocumented behavior, and I definitely need to do a better job of explaining what is going on here. The cause of this behavior is the implementation of the matching algorithm, which uses a heuristic to massively speed up the operation compared to a previous implementation, but which can lead to some quirks like this. But this is so low-level (i.e., at the level of the C++ code that does the matching), I didn't think explaining this in the documentation would be useful to most users. It is also quite unusual to get so many ties like this. But I will do more work to explain how the matching works so confusion like this doesn't arise in the future.

The algorithm `matchit()` uses for nearest neighbor matching on a propensity score is the following:
1. Arrange all units in order of the propensity score (`distance`) from smallest to largest.
2. For each treated unit, calculate the distance from the control unit immediately to itself and the one immediately to its right.
3. If the unit to its right is closer, select that as the match. Otherwise (including if there is a tie), select the one to its left.

Before version 4.5.1, a different algorithm was used, and is still used when `distance` is a suppled as a matrix or as a distance matrix function (e.g., `"mahalanobis"`) or `mahvars` is specified. The algorithm is as follows:
1. For each treated unit, compute the distance between it and all control units.
2. Select as a match the control unit with a minimum distance. In the case of ties, select the control unit earliest in the dataset.

In both cases, we match treated units in order of the propensity score from largest to smallest; this is controlled by the `m.order` argument, which is well documented. In the case of ties, the treated unit earlier in the dataset will get its match first.

Using algorithm 1 can lead to speed-ups of 600% times because for each treated unit, you only need to compute the distance between it and the two nearest control units, whereas in algorithm 2, you need to compute the distance between each treated unit and all other control units. Although this is a quick operation, in algorithm 2, you have to determine whether all those control units are eligible to be used as matches before computing their distance, whereas with algorithm 1, all checks only need to appear on the two closest units to the treated unit.

I incorrectly explained what was going on in @harttu's question above. At the end of this reply, I will explain how to understand why a given pair of units is matched in the case of ties and near ties.

To see how algorithm 1 works, it is useful to sort the data by `distance`, which is what `matchit()` does internally before the matching. When sorting in the case of ties, the original order of the dataset will be preserved. Using the original data to match, then displaying all the units after sorting by `distance`, we see the following:

```
    id age group cancer feature   distance weights subclass  diff
5  102  29     B   TRUE       0 0.06209728       0     <NA>    NA
4  101  28     A   TRUE       0 0.06209728       0     <NA> FALSE
6  103  30     C   TRUE       0 0.06209728       0     <NA> FALSE
1    1  19     A   TRUE       1 0.21948832       1        1 FALSE
2    2  20     B   TRUE       1 0.21948832       1        2  TRUE
10 301  19     A  FALSE       0 0.21948832       1        1  TRUE
11 302  20     B  FALSE       0 0.21948832       1        2  TRUE
13 401  19     A   TRUE       0 0.21948832       0     <NA>  TRUE
14 402  20     B   TRUE       0 0.21948832       0     <NA>  TRUE
3    3  21     C   TRUE       1 0.21948832       1        3 FALSE
12 303  21     C  FALSE       0 0.21948832       1        3  TRUE
15 403  21     C   TRUE       0 0.21948832       0     <NA>  TRUE
7  201  17     A   TRUE       0 0.27943777       0     <NA> FALSE
8  202  18     B   TRUE       0 0.27943777       0     <NA> FALSE
9  203  19     C   TRUE       0 0.27943777       0     <NA>  TRUE
```
You'll notice that IDs 1, 2, and 3 are not next to each other. This is because of infinitesimal differences in their propensity scores due to numerical imprecision; nothing we can control. I have added a column `diff` that corresponds to whether the `distance` of the corresponding unit is exactly equal to the `distance` value of unit just before it. What we find is actually that units 1 and 2 have exactly the same propensity score, but unit 3 has a propensity score that is slightly greater. That means we expect unit 3 to get its match first (because `m.order = "largest"` by default), then unit 1 (because it is earlier in the dataset than unit 2), then unit 2. Note that the order of `subclass` corresponds to the order of the observation in the dataset supplied to `matchit()`, not the order the units are matched (so unit 3 is in subclass 3 because it appeared as the third treated unit in the dataset, even though it is matched first).

For unit 3, it looks to left and sees unit 402, and it looks to its right to see unit 303. You might expect that unit 3 would be matched to unit 402, which is to its left, but actually unit 3 is closer to unit 303:
```
> m_ddd_data$distance[m_ddd_data$id == 303] == m_ddd_data$distance[m_ddd_data$id == 3]
[1] TRUE
> m_ddd_data$distance[m_ddd_data$id == 402] == m_ddd_data$distance[m_ddd_data$id == 3]
[1] FALSE
```
Again, this is due to numeric imprecision. So in this case, for unit 3, there is no tie between units 402 and 303; 303 is closer.

Now, let's reverse the dataset, do the match, then sort by `distance` again.

```
    id age group cancer feature   distance weights subclass  diff
4  101  28     A   TRUE       0 0.06209728       0     <NA>    NA
6  103  30     C   TRUE       0 0.06209728       0     <NA> FALSE
5  102  29     B   TRUE       0 0.06209728       0     <NA>  TRUE
13 401  19     A   TRUE       0 0.21948832       0     <NA> FALSE
10 301  19     A  FALSE       0 0.21948832       1        3  TRUE
1    1  19     A   TRUE       1 0.21948832       1        3  TRUE
14 402  20     B   TRUE       0 0.21948832       0     <NA> FALSE
11 302  20     B  FALSE       0 0.21948832       1        2  TRUE
2    2  20     B   TRUE       1 0.21948832       1        2  TRUE
15 403  21     C   TRUE       0 0.21948832       0     <NA> FALSE
12 303  21     C  FALSE       0 0.21948832       1        1  TRUE
3    3  21     C   TRUE       1 0.21948832       1        1  TRUE
7  201  17     A   TRUE       0 0.27943777       0     <NA> FALSE
8  202  18     B   TRUE       0 0.27943777       0     <NA> FALSE
9  203  19     C   TRUE       0 0.27943777       0     <NA> FALSE
```
Unit 3 looked to its left to find unit 303, which was without a doubt closer than unit 201, so it receives 303 as a match again. Unit 2 looked to left to find unit 302, looked to its right to find unit 403, and chose unit 302. Note this is not a tie; unit 302 is actually closer. But actually the tie is between units 402 and 302; they are both equally close to unit 2. Because in the dataset sorted in reverse order, unit 403 comes before unit 302, and unit 302 comes before unit 2, 302 is selected as a match to 2. So this explains why for your first two runs, we always get the same results. Regardless of the direction the data are sorted, exact matches will always be near each other, and 300s will always be closer to 1-3 than 400s are.

However, when I sort the data by cancer, I do not get the same results as you. See the matched dataset sorted by `distance` below:
```
    id age group cancer feature   distance weights subclass  diff
4  101  28     A   TRUE       0 0.06209728       0     <NA>    NA
5  102  29     B   TRUE       0 0.06209728       0     <NA> FALSE
6  103  30     C   TRUE       0 0.06209728       0     <NA> FALSE
13 401  19     A   TRUE       0 0.21948832       1        3 FALSE
1    1  19     A   TRUE       1 0.21948832       1        3  TRUE
10 301  19     A  FALSE       0 0.21948832       0     <NA>  TRUE
15 403  21     C   TRUE       0 0.21948832       1        1 FALSE
3    3  21     C   TRUE       1 0.21948832       1        1  TRUE
12 303  21     C  FALSE       0 0.21948832       0     <NA>  TRUE
14 402  20     B   TRUE       0 0.21948832       1        2 FALSE
2    2  20     B   TRUE       1 0.21948832       1        2  TRUE
11 302  20     B  FALSE       0 0.21948832       0     <NA>  TRUE
7  201  17     A   TRUE       0 0.27943777       0     <NA> FALSE
9  203  19     C   TRUE       0 0.27943777       0     <NA> FALSE
8  202  18     B   TRUE       0 0.27943777       0     <NA>  TRUE
```
Now I get that 3 is matched to 403, 2 is matched to 402, and 1 is matched to 401. This is makes sense given the orderings and is what I would expect. Each unit is exactly equally close to the units the left and right of it, so it chooses the unit on the left (which in this case is the unit with `cancer == TRUE` since we sorted that way). So I can't explain why you are seeing what you are seeing in your final match; I am unable to replicate that. I am running an Intel-based Mac using `MatchIt` 4.5.5. Maybe there is some difference in the numerical precision on your system that is creating this difference.

Regardless, you can do the following to understand what is going on. First, sort your input dataset however you want, and feed it to `matchit()`. Return the matched dataset, including the unmatched units, by setting `drop.unmatched = FALSE` in the call to `match.data()`.  Sort the matched dataset by `distance`. For any pair of adjacent units, check whether the `distance` values are *actually* equal to each other, which you can check manually or by using `diff(.) == 0`. Just because they appear equal based on the first several digits and theoretically should be equal does not mean R reads them as equal due to numerical imprecision. The only `distance` values you can confidently assume are exactly equal are those corresponding to units with identical values of the covariates. This is why it appears that some sort of exact matching is going on; in fact, `matchit()` doesn't use the covariate values at all in the match except to compute the propensity scores.

**Comment by tommmmi** [comment]
Thank you for your reply. I appreciate your effort! This is very interesting.

Yesterday I was using R 4.1.3 on Ubuntu-based environment with MatchIt version 4.5.4, but I also have Intel-based Mac available and as now running the same script, I get the same result as you are (3 matched to 403, 2 to 402 and 1 to 401) using R 4.3.1 with MatchIt version 4.5.5 !

I happen to have also M1 Mac running R 4.2.3 with MatchIt version 4.5.5 and it yields the same 3-403, 2-402, 1-401 result.

I upgraded the 4.5.4 to 4.5.5 on the Ubuntu system but it still produces this "wrong" result of 3-401, 2-402, 1-403 pairs. Unfortunately at the moment, I cannot upgrade the R version on that system, but I doubt that it would affect the numeric precision that seems to be causing this?

**Comment by ngreifer** [comment]
Hi Tommi,

Are you able to follow the instructions in my last paragraph to try to see whether adjacent values of `distance` are equal to each other when sorting by `distance`? You should be able to run the following code:

```r
m_ddd_data <- match.data(m_ddd, drop.unmatched = FALSE)
m_ddd_data <- m_ddd_data[order(m_ddd_data$distance),]
m_ddd_data$diff <- c(NA, diff(m_ddd_data$distance == 0))

m_ddd_data
```
This will indicate whether adjacent values have exactly the same propensity score. I would expect matches only to occur between units with exactly the same propensity score. If your Ubuntu machine indicates a different pattern of results from that above, then we know the answer is in how it processes the propensity scores, which are generated purely by `predict.glm()` and not by `matchit()`.
