### ISSUE TITLE
Can glm.nb be used after running matching with Matchit?

### ISSUE THREAD

**Issue by pychan-polly** [kosukeimai/MatchIt#183]
This is technically not an issue but more of a question... I would like to use a model object from glm.nb in avg_comparisons() to obtain a ATT estimate for a matched sample. I read through this page (https://kosukeimai.github.io/MatchIt/articles/estimating-effects.html) which has been very helpful but doesn't mention negative binomial models at all. I was actually able to run my codes with glm.nb object in avg_comparisons() without any error but would like to check/see if anyone has experience with this.

**Comment by ngreifer** [comment]
In order to estimate the effect and adjust for uncertainty correctly, the model fitting function must accept weights (unless 1:1 matching is used), must be compatible with a cluster-robust variance computed by `sandwich::vcovCL`, and must have a working predict method as implemented in avg_presictions(). I believe all those are true with glm.nb(), but that is a question for the authors of those packages. That said, you should always prefer quasi-Poisson regression to negative binomial regression, especially since you are already using a robust SE.
