### ISSUE TITLE
ATT estimate in survival analysis

### ISSUE THREAD

**Issue by arielhasidim** [kosukeimai/MatchIt#190]
In the [_Estimating Effects After Matching/Survival Outcomes_](https://kosukeimai.github.io/MatchIt/articles/estimating-effects.html#survival-outcomes) article, there is the use of `coxph()` with attributes for `weight`, `cluster` and `robust`, but unlike the standard case, we do not pass down a `newdata` equivalent to assess the effect on the treated only.

Does this mean we get the estimate for ATE instead?

**Comment by ngreifer** [comment]
The ATE estimated in the matched sample or the sample with ATT weights applied is the ATT. Indeed, that's one of the points of matching (to make the control group resemble the treated group so that the whole sample resembles the treated group, which means the effect estimated in the whole sample is interpretable as the ATT). The procedure for `coxph()` doesn't allow for marginal effects or the inclusion of covariates in the outcome model. Conceptually, it is similar to running a t-test in the matched sample, which obviously targets an estimated generalizable only to the matched sample. If you want to include covariates in your Cox model, you will have to do extra work to arrive at an interpretable marginal estimand corresponding to the ATT, and that work is beyond the scope of the vignette unfortunately.

**Comment by arielhasidim** [comment]
@ngreifer Thank you!
