### ISSUE TITLE
Allow matching on list variables

### ISSUE THREAD

**Issue by TimOvereem** [kosukeimai/MatchIt#37]
When trying to match using a variable that's a list I get the error `invalid type (list)`.

If list variables were supported using some metric like `at least 1 exact match of elements between two lists` more powerful analysis could be done.

There are some hacky workarounds I can think of, but would appreciate if this can be supported in a first class way or if there are any commonly-used workarounds someone can share!

**Comment by ngreifer** [comment]
I like the idea of a partial matching by at least one element in a list variable, but I'm not inclined to add that into `MatchIt` because list variables do not play a clear role in computing a distance metric such as the propensity score difference or Mahalanobis distance and adding support for them would require a complicated restructuring of the code and specialized routines for what is a very uncommon problem. `MatchIt` is not designed for highly customized matching specifications like the one you described, but you might be able to implement a version of it in `Matching` or `optmatch` by manually restricting certain matches. 

In `Matching`, you could use the `restrict` argument in the call to `Match()` after computing the restriction matrix, which you would have to do manually by looping through each treated and control unit. In `optmatch`, you could create a distance matrix using `match_on()` and then manually set distance between units that do not share a value of the list variable to `Inf` to prevent them from being matched. You would then supply that matrix to `fullmatch()` or `pairmatch()`.
