### ISSUE TITLE
Error: The argument to 'distance' must be a string of length 1 when using matchit with default arguments

### ISSUE THREAD

**Issue by JohannesWiesner** [kosukeimai/MatchIt#45]
I want to use the `matchit` function with the default arguments (that is, I only provide the function with the `data` and the `formula` argument):

This is how my data frame `site_df` looks like (only the first 14 rows are shown):

![dataframe](https://user-images.githubusercontent.com/48254290/99534650-08929200-29a8-11eb-8867-84d4f48d698d.png)

```
formula = as.formula("group_boolean_inversed ~ sex_boolean + age")
m.out <- matchit(formula=formula,
                 data=site_df)

site_df_matched <- get_matches(m.out,site_df)
```

wich produces this error:

```Fehler: The argument to 'distance' must be a string of length 1.```

I am using the CRAN-downloaded version of MatchIT (‘4.0.0.9000’). The devtools version as suggested in #41 didn't work on my machine due to some DLL-issues.

**Comment by ngreifer** [comment]
Hi Johannes,

That's because you supplied `site_df` as the second argument to `get_matches()`, and the second argument corresponds to the `distance` argument. Because `site_df` is not a string of length 1, you are getting that error, which is correct and not a bug. If you want to supply `site_df` to `get_matches()`, you must do so using the `data` argument. So, your call should be 
```
site_df_matched <- get_matches(m.out, data = site_df)
```
When matching without replacement, as you have done, it typically makes more sense to use `match.data()`, which does the same thing but may be a little faster and will retain the original order of the data.

**Comment by JohannesWiesner** [comment]
Ah, sorry @ngreifer, my fault. I guess I got on the wrong track, because I played around with different values for the `distance` arguments in the `matchit` function. So when I added `distance = 'mahalanobis` to to `matchit` function and then called `get_matches(m.out,site_df)`, I didn't get the warning. As a consequence, I thought that something is buggy in the `matchit` function and thus didn't come up with the idea to also check the `get_matches` function.
