### ISSUE TITLE
calculating total% reduction in bias

### ISSUE THREAD

**Issue by priyankapri** [kosukeimai/MatchIt#65]
Though the package allows for assessing bias reduction for individual variables pre and post matching. However, it does not allow to calculate overall total bias reduction from pre matching to post matching. I was wondering if you can help me understand if this information is accessible or can be computed using the information in the MatchIt package.

**Comment by ngreifer** [comment]
To know about "total bias reduction", you would have to know what the true unbiased effect is. We never know this; otherwise, we wouldn't have to do statistics to figure it out. You can easily compute an effect estimate before and after matching using the model of your choice and compare them, but that doesn't represent the decrease in bias due to matching, just how the estimate has changed. Is there a specific value you have read about somewhere that you want to be able to compute?
