### ISSUE TITLE
Missing levels on my covariates

### ISSUE THREAD

**Issue by wimul** [kosukeimai/MatchIt#72]
I need some help, please. I used MatchIt and my matching object looks like this:
 - method: 1:1 optimal pair matching
 - distance: Propensity score
             - estimated with logistic regression
 - number of obs.: 10444 (original), 7774 (matched)
 - target estimand: ATT
 - covariates: factor(year), factor(Site), factor(Breeder), Region

I'm struggling to interpret the coefficients from coeftest( ) because for year, site and breeder, the computation is dropping more than one level. More precisely, for year, which has 15 different years, it is dropping 2; for site, which has 31 different site, it is dropping 5. The factor breeder has 3 and it's dropping just 1 what I think makes sense. 

Thanks in advance for your help.

**Comment by ngreifer** [comment]
Levels of a factor are dropped in a regression when there are no units with those values or when they are linearly dependent on other variables (including levels of the same factor). What likely happened is that the matching changed the distribution of the covariates to yield one of the above phenomena. For example, it may be that after matching, all of the observations for a given breeder have the same region, and vice-versa, so that that level of breeder is redundant after including region in the model. You should examine the `match.data()` output to see if a phenomenon of this type is occurring.

**Comment by wimul** [comment]
Thanks, @ngreifer. I'll check and will let you know.
