### ISSUE TITLE
Mahalanobis and Variable Ratio matching

### ISSUE THREAD

**Issue by gui-salome** [kosukeimai/MatchIt#79]
(thanks for developing this package and the really amazing documentation)

When finding matches with `distance="mahalanobis"` and `method="nearest"`, is it possible to have variable ratio matching? The documentation for the [nearest method](https://kosukeimai.github.io/MatchIt/reference/method_nearest.html) says that is not possible with Mahalanobis. Is that still the case? I was wondering what is the main road block for that? Wouldn't it be possible to find closest k matches given a caliper value?

Thanks for helping!

**Comment by ngreifer** [comment]
Hi Guilherme,

Thank you for the kind words. The implementation of variable-ratio matching with `method = "nearest"` follows that of [Ming and Rosenbaum (2000)](https://doi.org/10.1111/j.0006-341X.2000.00118.x), which is called "extremal" matching and uses the propensity score to order units to determine how many matches each unit should get. No calipers are involved. Because with `distance = "mahalanobis"`, no propensity score is involved, there is no way to order the units and determine how many matches each treated unit should get.

There are other ways to do variable-ratio matching. If you set `ratio` greater than 1 and a caliper such that some treated units receive one match (i.e., because only one control unit was within the caliper) and other treated units receive multiple matches (i.e.. because multiple control units were within the caliper), this is a form of variable-ratio matching and one you can do with `distance = "mahalanobis"`. This seems to be the method you are proposing. The restriction against variable-ratio matching with `distance = "mahalanobis"` comes from trying to using `min.controls` and `max.controls` to activate extremal matching, not the incidental variable-ratio matching that comes from using a caliper and a `ratio` greater than 1.

Because optimal matching does not require ordering the units, you can perform extremal matching with `distance = "mahalanobis"` when using `method = "optimal"` by setting `max.controls` and `min.controls`. The algorithm will automatically figure out how many matches each treated unit will receive.

**Comment by gui-salome** [comment]
> Hi Guilherme,
> 
> Thank you for the kind words. The implementation of variable-ratio matching with `method = "nearest"` follows that of [Ming and Rosenbaum (2000)](https://doi.org/10.1111/j.0006-341X.2000.00118.x), which is called "extremal" matching and uses the propensity score to order units to determine how many matches each unit should get. No calipers are involved. Because with `distance = "mahalanobis"`, no propensity score is involved, there is no way to order the units and determine how many matches each treated unit should get.
> 

Interesting, thanks for the explanation and the reference.

> There are other ways to do variable-ratio matching. If you set `ratio` greater than 1 and a caliper such that some treated units receive one match (i.e., because only one control unit was within the caliper) and other treated units receive multiple matches (i.e.. because multiple control units were within the caliper), this is a form of variable-ratio matching and one you can do with `distance = "mahalanobis"`. This seems to be the method you are proposing. The restriction against variable-ratio matching with `distance = "mahalanobis"` comes from trying to using `min.controls` and `max.controls` to activate extremal matching, not the incidental variable-ratio matching that comes from using a caliper and a `ratio` greater than 1.
> 
> Because optimal matching does not require ordering the units, you can perform extremal matching with `distance = "mahalanobis"` when using `method = "optimal"` by setting `max.controls` and `min.controls`. The algorithm will automatically figure out how many matches each treated unit will receive.

I saw this part of the documentation, using the "optimal" method we can have a variable-ratio matching with Mahalanobis distance. Does it make sense to allow `max.controls=Inf` (match as many as possible, considering the optimization criteria)?

Thanks for helping and great work with this and the other packages you developed!

**Comment by ngreifer** [comment]
You can specify `ratio` as some very large finite number (not `Inf`) with a caliper using `method = "nearest"`. This will match all units within the caliper to each treated unit. This is a workaround to do what you want to do; the high `ratio` is just used to allow as many matches to each treated unit as are available and does not place a restriction on the number of matches. This method is known as radius matching in the literature. You cannot do this with `method = "optimal"` because optimal matching does not support a caliper (this is a problem with the `optmatch` package, not with `MatchIt`).

So, to summarize the options for variable-ratio matching:

- To do radius matching, set `method = "nearest"`, `ratio` to a large finite value, and `caliper` to the desired radius size. This will match all controls within each treated unit's radius to that treated unit. Different treated units will receive different numbers of matches. This cannot be done with `method = "optimal"` because calipers are not supported.
- To do extremal matching, set `method = "nearest"` or `method = "optimal"`, set `ratio` to a value greater than 1, and set `max.controls` to a value greater than `ratio`. To do this with Mahalanobis distance matching, `method = "optimal"` must be used.
- To do a version of full matching where each treated unit receives one or more matches and all control units are matched, you can do the above but set `ratio = n0/n1` where `n0` is the number of available control units and `n1` is the number of available treated units, and set `max.controls` to some number greater than this. This will match all available controls to the treated units. The `max.controls` argument controls how the control units are allocated. Calipers can be used when `method = "nearest"`.
- If you want to do the version of full matching described above but letting the algorithm decide how the control units are allocated, you can use `method = "full"` with `min.controls = 1` and `max.controls = Inf`, which will assign at least one control unit to each treated unit and use all control units in the match. Calipers cannot be used with this specification.
- If you want to do standard full matching, where all treated and control units are assigned to subclasses that contain either exactly one treated or exactly one control unit, simply set `method = "full"`. Calipers can be used with this specification.

**Comment by gui-salome** [comment]
> You can specify `ratio` as some very large finite number (not `Inf`) with a caliper using `method = "nearest"`. This will match all units within the caliper to each treated unit. This is a workaround to do what you want to do; the high `ratio` is just used to allow as many matches to each treated unit as are available and does not place a restriction on the number of matches. This method is known as radius matching in the literature. 

Would this work with `distance="mahalanobis"`? This is exactly what I was looking for in the beginning, thanks for the help! It would achieve variable ratio matching (because of the cutoff set by the caliper). As I learned about the optimal method, I got more inclined to use it instead of nearest neighbors. 

> You cannot do this with `method = "optimal"` because optimal matching does not support a caliper (this is a problem with the `optmatch` package, not with `MatchIt`).

I saw that in the docs. Hopefully `optmatch` fixes it eventually. The downside of not having a caliper is that we cannot specify `ratio` as a large number and have a restricted version of full matching, where possibly not all control units are matched (because of the cutoff set by caliper). Basically, I would like to use as many controls as possible, as long as it makes sense with the optimization criteria and the distance isn't too large (caliper).

> So, to summarize the options for variable-ratio matching:
> 
> * To do radius matching, set `method = "nearest"`, `ratio` to a large finite value, and `caliper` to the desired radius size. This will match all controls within each treated unit's radius to that treated unit. Different treated units will receive different numbers of matches. This cannot be done with `method = "optimal"` because calipers are not supported.
> * To do extremal matching, set `method = "nearest"` or `method = "optimal"`, set `ratio` to a value greater than 1, and set `max.controls` to a value greater than `ratio`. To do this with Mahalanobis distance matching, `method = "optimal"` must be used.
> * To do a version of full matching where each treated unit receives one or more matches and all control units are matched, you can do the above but set `ratio = n0/n1` where `n0` is the number of available control units and `n1` is the number of available treated units, and set `max.controls` to some number greater than this. This will match all available controls to the treated units. The `max.controls` argument controls how the control units are allocated. Calipers can be used when `method = "nearest"`.
> * If you want to do the version of full matching described above but letting the algorithm decide how the control units are allocated, you can use `method = "full"` with `min.controls = 1` and `max.controls = Inf`, which will assign at least one control unit to each treated unit and use all control units in the match. Calipers cannot be used with this specification.
> * If you want to do standard full matching, where all treated and control units are assigned to subclasses that contain either exactly one treated or exactly one control unit, simply set `method = "full"`. Calipers can be used with this specification.

**Comment by ngreifer** [comment]
Performing radius matching as I described could be done with `distance = "mahalanobis"` but only if the calipers are on variables other than the propensity score, since no propensity score is included or estimated. To do Mahalanobis distance matching within propensity score calipers, you will have to use the `mahvars` argument. This is explained in the documentation. There is no way to apply a caliper to the Mahalanobis distance itself, though you can do so manually outside of `MatchIt` and supply the caliper-added Mahalanobis distance matrix back to `matchit()`. You said that you were interested in optimal matching, but this method only works with nearest-neighbor matching because it involves a caliper.

Is there is a reason you are resistant to standard full matching (i.e., `method = "full"`)? It uses all the controls, and calipers can be applied. Its only downside is that the effective sample size may be smaller than the number of treated units, but that is not always the case. In general, full matching performs better than other matching methods.

**Comment by gui-salome** [comment]
I tested the nearest-neighbor matching with Mahalanobis distance (I am not interested in propensity score at all) and setting calipers for each of the variables, and it works well. The benefit of nearest-neighbors is speed. With large datasets, the optimal methods (partial or full) can take a substantially longer time to run, and could be unfeasible depending on the number of units.

Standard full matching is an interesting approach, but I wonder what would happen if some of the test units had no reasonable matches.

**Comment by ngreifer** [comment]
I understand what you mean about speed. That definitely is the main benefit of greedy matching. Interesting findings in your dataset. Of course things may be different in different scenarios.

Feel free to close this issue if you feel like your questions have been answered.

**Comment by gui-salome** [comment]
Thanks for helping and for the discussion!
