### ISSUE TITLE
Error: object of type 'closure' is not subsettable

### ISSUE THREAD

**Issue by aniketd006** [kosukeimai/MatchIt#86]
Hi I am trying use the MatchIt function and I am getting the following error:

Error in `*tmp*`[fit$pivot] : object of type 'closure' is not subsettable
In addition: Warning messages:
1: In glm.fit(x = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  :
  non-finite coefficients at iteration 1
2: glm.fit: algorithm did not converge

The line of code that I am running is:

modelOutputRx = matchit(model, data=allMbrsRx, method="nearest", ratio=3, caliper=0.2, discard="both")

'model' has the model description in y ~ x1 + x2 + x3 + ... format

Do you know how do I resolve this issue? Or why is this happening?

**Comment by ngreifer** [comment]
I'm not sure why this is happening, but it is probably not a `MatchIt` problem. Trying running a `glm()` model with your data, i.e., `glm(model, data = allMbrsRx, family = binomial)`. If you get the same error, then there is something wrong with your model. You can ask about it on StackOverflow (if you do, include the actual `model` formula because that's where the error probably is).

**Comment by aniketd006** [comment]
You were right. It was nothing to do with the matchIt() function. There was some issue with the underlying data allMbrsRx. I converted the dataset into a data frame explicitly using as.data.frame(allMbrsRx) and the issue go resolved. Thank you for your prompt response!
