### ISSUE TITLE
"Error: (from optmatch) missing value where TRUE/FALSE needed" when `method = "full"` in version 4.3.0

### ISSUE THREAD

**Issue by xingzhong-jin** [kosukeimai/MatchIt#88]
It seems there is an error in the code for the wrapper of full matching for version 4.3.0.

I can run the syntax below in 4.2.0 but not in 4.3.0.

`matchit(formula = arm ~ sex + race + kl + bmicat + kpmed + smoker + bmi + womadl + gluc + chon + comorb + cesd + pase, exact = ~sex + race + kl + bmicat + kpmed + smoker, data = dat, estimand = "ATE", method = "full", distance = "glm")`

![Screen Shot 2021-09-17 at 2 57 37 pm](https://user-images.githubusercontent.com/12545106/133727008-f0b38904-eec8-4904-af8a-0c9de81815c3.png)

Below is a quick snapshot of the dataset used. Some covariates have missing values and I used simple single imputation and created a missing indicator ({.var}_na) in the dataset. 

![Screen Shot 2021-09-17 at 3 03 51 pm](https://user-images.githubusercontent.com/12545106/133727529-fad945b1-6d94-4a19-8e63-ded2114da1f6.png)
----

I tried to re-create the same error message using the lalonde dataset, but unfortunately failed...so I am not quite sure what exactly the underlying issue is. 

Any helps will be appreciated.

**Comment by ngreifer** [comment]
Wow, I'm so sorry about that! Would you be willing to send me your data so I can look into this? I have a feeling it might be due to the exact matching variables, since that's the only change related to full matching I made between the two versions. If you remove some of the full matching variables, does the error go away?

**Comment by xingzhong-jin** [comment]
> Wow, I'm so sorry about that! Would you be willing to send me your data so I can look into this? I have a feeling it might be due to the exact matching variables, since that's the only change related to full matching I made between the two versions. If you remove some of the full matching variables, does the error go away?

Hi Norah, thanks for the rapid response! I think you are right, it is due to the exact matching variables. The error goes away once I remove the `exact` argument. I am happy to send you the data in private to look deeper into the error. What's the best way to send?

**Comment by ngreifer** [comment]
You can either attach a file directly into the GitHub comment or send me a link to download the file, e.g., using we.tl or Dropbox. Thanks!

**Comment by xingzhong-jin** [comment]
> You can either attach a file directly into the GitHub comment or send me a link to download the file, e.g., using we.tl or Dropbox. Thanks!

Hi Norah, please use the link below to download the dataset. 
https://bit.ly/2XsLIPI

I am also copying the session info below for your info.

> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.5.2
Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
 [1] ggdag_0.2.3        forcats_0.5.1      stringr_1.4.0      dplyr_1.0.7       
 [5] purrr_0.3.4        readr_2.0.1        tidyr_1.1.3        tibble_3.1.4      
 [9] ggplot2_3.3.5      tidyverse_1.3.1    cobalt_4.3.1       MatchIt_4.3.0     
[13] kableExtra_1.3.4   knitr_1.34         janitor_2.1.0      DataExplorer_0.8.2
[17] here_1.0.1

**Comment by ngreifer** [comment]
Thank you so much! I fixed this in the development version of `MatchIt`, which you can install using `devtools::install_github("ngreifer/MatchIt")`. Hopefully it works for you.

The issue was caused by some of your exact matching strata having only one treated and one control unit. There is a calculation in `optmatch` that involves dividing a number by 2 less than the number of units, which ended up dividing by zero and causing the error when that value was passed to an `if` statement. I submitted this as an issue to the `opmatch` maintainers but implemented a simple workaround in `MatchIt`. Obviously if there are only two units, they should be matched to each other. Thank you for telling me about this bug.

**Comment by msghankinson** [comment]
Hi Noah,

I'm receiving the same error with full matching even after downloading the developer version using the devtools code you supplied above. I've attached a data sample which already filters down to exact matches which have at least one treated unit and one control unit. Do you have any ideas of why the workaround isn't working in this case?

Very much looking forward to using MatchIt otherwise!
[matchit_sample.csv](https://github.com/kosukeimai/MatchIt/files/7614014/matchit_sample.csv)

![Screen Shot 2021-11-28 at 12 23 10 PM](https://user-images.githubusercontent.com/12862415/143778891-6f82b8a5-b908-432d-8bf7-69a9ea3a773e.png)
.

**Comment by ngreifer** [comment]
I don't get an error when running that code. Can you try using the version of `MatchIt` that is on CRAN? I just updated it a few days ago.

**Comment by msghankinson** [comment]
Wow. I don't know why it wasn't working initially with the CRAN version, but it works now. Thank you for the quick response!
