### ISSUE TITLE
How to understand Caliper on different covariates? Nearest with Mahalanobis 

### ISSUE THREAD

**Issue by omerdar** [kosukeimai/MatchIt#89]
Hi
I'm trying to find "spare" controls for my primary control group (that I found via cardinality method)
I need to find the best pairs or subclass that are matched to each one of my primary control units, and I don't care here about the balance at the matched group level, or in each subclass. (and I don't want this balance to reduce the quality of each pair or subclass). 
 
I'm using this code - 

`n <- matchit(Primary ~ Retreat_Days+ Regualr_Practice_Total_Hours+ Group_age, data = secondary_match,
             method = "nearest", distance = "mahalanobis",ratio = 5,
             caliper = c(Retreat_Days = 0.3,Regualr_Practice_Total_Hours = 0.2,Group_age = 1.1),std.caliper=TRUE)

These caliper values enable me to have at least one match unit for each primary unit. (or more if possible).
I have some questions:

1. The **caliper** means that the difference between a primary unit to each matched control unit in the same subclass, is maximum x1 standard deviation for covariate X1, and maximum x2 std for covariate X2, etc? (x1, x2, are my parameters in the caliper vector)

2. If I change the **ratio**, it could influence the quality/difference of the other pairs in the same subclass? or it's orthogonal? 

3. How can I **prioritize in each subclass** who is the best pair? (of course, by a standard rule and not by looking at the covariates of the specific unit). 

4.  if I change the method from "nearest" to "full", would I get all the optional pairs that stand in the caliper threshold/criteria? 
it seemed that I get a large subclass with 20+ matched units, and then many other subclasses become only pairs, even that before (with nearest and ratio = 5) the algorithm could find 5 good matched for the same primary unit. 

Thanks a lot for your help!

**Comment by ngreifer** [comment]
1. Yes, that's correct.
2. Changing the ratio should not affect the composition of other subclasses because all units get one match before the first unit gets its second match, etc. That is, if you did a 1:1 match, removed all the matched controls, and did another 1:1 match, that would be equivalent to doing a 2:1 match.
3. You could look at the Mahalanobis distance between units within a pair. Because you're doing nearest neighbor matching, the first unit to be matched will always be the best match, so doing a 1:1 match would be sufficient. To demonstrate this to yourself, you will need to compute the Mahalanobis distance manually yourself. If you are decent at programming, you can use R's `mahalanobis()` function, but `optmatch::match_on()` can also do it. Once you have that, you can examine the Mahalanobis distances between each primary unit and its matched controls and pick the smallest one.
4. You should get a matched set that minimizes the total distance between each primary unit and its matched controls. because it optimizes a global rather than local criterion, it is possible that some primary units may not be matched to their closest control, which would otherwise occur with nearest neighbor matching. It's important to note that with full matching, it's possible to have many primary units and a single control unit in the same subclass, which does not seem like what you want. To prevent, you should set `min.controls = 1` to ensure that each subclass only has one primary unit. You can also set `max.controls` to control the size of the subclasses. If all you want is the single closest control unit to each primary unit, though, there is no benefit to full matching, and 1:1 nearest neighbor matching should be sufficient.

I think you should probably close your question on CrossValidated if I have answered it here. In general, for questions about specific packages, especially when the package is fairly small like `MatchIt`, you should just ask the maintainers directly rather than post on CV.

**Comment by ngreifer** [comment]
I'm glad it was helpful! I think I understand what you're doing. It seems like you want "backups" in case your primary control units drop out. It makes sense that you would want units close enough to accurately replace the lost units.

I think it would be a good idea to perhaps increase `min.controls` to something like 2 or 3 to make sure there are backups if you are using full matching.

Full matching minimizes the total distance between all primary units and all control units within each subclass, combined across the entire sample. In this sense, the method is optimizing a global (i.e., full sample) criterion, rather than optimizing the quality of each individual match. Nearest neighbor matching, however, does optimize the quality of each individual match, so at a given point in the matching procedure, the primary unit will be matched to its closest control unit that is available. I actually think nearest-neighbor matching would be better suited for your case because the quality of the 5th and 6th matches, for example, is less important than the quality of the first match, which, if there is dropout among the primary units, would be the first units to replace them, whereas the 5th and 6th matches are less likely to play a role in your final analysis. Full matching treats all matches equally, but nearest neighbor matching prioritizes the first matches, so you will get better first matches with nearest-neighbor matching.

If these matched control units exist for the sole purpose of replacing primary units that have dropped out, I think it actually makes more sense to wait until the dropout occurs and then perform the matching. That way if a primary unit doesn't drop out, it won't be hoarding possibly good matched controls aways from other primary units that have dropped out and need replacement. 

If you want to have the matches ready at the beginning of the study, you could also do matching with replacement. here's how this would work:
Set `replace = TRUE` with `method = "nearest"`, but set `ratio` to a very high number (e.g., the totol number of control units available). Extract the `match.matrix` output of the resulting `matchit` object. When a primary control unit drops out, use its matched control, which is the unit in the first column of `match.matrix` in the primary unit's row. If another primary unit drops out, use its first matched control unit. But, because you did matching with replacement, remember to skip over any control units that have already been used.

**Comment by omerdar** [comment]
Thanks! 
It works great and is exactly what I need. 

Another minor point  - until now I used match.data() to find the matched unit by using the 'subclass' column, but when I'm trying your good idea and set replace = TRUE, the subclass column in the match.data() disappear. Anyway, I get the subclass column in the output of get_match() and also can use the match.matrix as you offered for findings the matched units. 

thanks again, you really helped me :)

**Comment by ngreifer** [comment]
That's explained in the documentation for `match.data()`, which I encourage you to read carefully. I would recommend using the `match.matrix` component of the `matchit` output object instead, since that is very clear about which units are matched to which.
