### ISSUE TITLE
Assessing balance of skewed distribution

### ISSUE THREAD

**Issue by omerdar** [kosukeimai/MatchIt#95]
hi
I finished data collection and I want to compare my final 2 treated and matched-control group.
1) Should I report in a paper about assessing the match before dropout and replacements of control units due to dropout? 
or only about the comparison of the final groups? 
2) My covariates are skewed, there is any reason to conduct log transform on the covariates for having a normal distribution, for assessing the match quality? (I assume standardized mean difference [Cohen's D] is not informative \ relevant for skewed distribution, or other significance test examine the differences between the control and treated distribution per covariate)
3) Empirical CDF Statistics (eCDFs) could be the best statistic to asses the match quality for skewed data?  there is any significance test I can use for it? or a norm for a "good value"? (I got every eCDFs mean ~0.03-0.07, is it good?)
what's the meaning of eCDFs mean for distance?  

Thank you very much
Omer Dar

**Comment by ngreifer** [comment]
Hi Omer,

1. You should explain in detail how you got from your initial dataset to the sample you used to estimate the effect. I'm not really sure what you mean, but more detail is always better. try to imagine yourself as a skeptical reader of your paper; what would you want to see, and what would make you cautious about interpreting the results?
2. You should check balance on every transformation of your covariates you think could be relevant to the outcome. The fact that the variable is skewed has nothing to do with it. You are not calculating Cohen's d to describe an effect size; you are simply examining the difference in means standardized to a uniform scale. You should compare the mean, the mean of the square, etc., not because of the shape of the distribution of the variable, but because good covariate balance requires balance on all features of the distribution. Do not use significance tests to compare the distributions of covariates between groups. There is no need to treat skewed variables differently.
3. ECDF statistics should be used for all variables as a complement to standardized mean differences and variance ratios. They are not particularly more effective for skewed variables. ECDF mean is not a well-understood measure and is in `MatchIt` mostly for historical reasons. You should use eCDF max, also known as the Kolmogorov-Smirnov (KS) statistic.  There is no guideline for what counts as a good value for eCDF max. I usually say <.1 is good.

Noah
